{{- if or .Values.secrets.openaiApiKey .Values.secrets.slackWebhookUrl -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "seneca.fullname" . }}-secrets
  labels:
    {{- include "seneca.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.openaiApiKey }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.slackWebhookUrl }}
  SLACK_WEBHOOK_URL: {{ .Values.secrets.slackWebhookUrl | b64enc | quote }}
  {{- end }}
{{- end }} 